/**
 * ============================================================
 * DD Laundry - Main JavaScript File
 * js/main.js
 *
 * PURPOSE:
 * Central JavaScript file for all DD Laundry frontend pages.
 * Provides XSS-safe DOM helpers, CSRF-aware API communication,
 * UI components (modals, toasts, OTP inputs), form handling,
 * and initialization routines. Loaded on every page.
 *
 * ============================================================
 * SECTION 1: XSS-SAFE DOM HELPERS (Lines 5-18)
 * ============================================================
 *
 * escHtml(str)
 *   - Escapes HTML special characters to prevent XSS
 *   - Uses DOM API (createElement + createTextNode) for safety
 *   - Returns safe string for use in innerHTML
 *   - Example: escHtml('<script>') returns '&lt;script&gt;'
 *
 * setTextSafe(el, text)
 *   - Safely sets text content of an element
 *   - Uses textContent property (never innerHTML)
 *   - Prevents XSS by treating content as plain text
 *   - Example: setTextSafe(div, user.name) is always safe
 *
 * safeHTML(el, html)
 *   - Sets innerHTML ONLY for trusted, developer-written templates
 *   - NEVER use with user-generated content
 *   - Used for static UI templates (icons, structure)
 *   - Example: safeHTML(container, '<div class="card">...</div>')
 *
 * ============================================================
 * SECTION 2: CSRF TOKEN MANAGEMENT (Lines 20-24)
 * ============================================================
 *
 * getCSRFToken()
 *   - Reads CSRF token from <meta name="csrf-token"> tag
 *   - Token is generated by PHP on each page load
 *   - Used in all AJAX POST requests for CSRF protection
 *   - Returns empty string if meta tag not found
 *
 * ============================================================
 * SECTION 3: API COMMUNICATION HELPERS (Lines 26-49)
 * ============================================================
 *
 * apiCall(url, data)
 *   - Makes authenticated POST request to backend API
 *   - Automatically appends CSRF token to FormData
 *   - Returns parsed JSON response
 *   - Returns error object on network failure
 *   - Used for: login, register, place order, profile update, etc.
 *   - Example: await apiCall('./php/auth.php', {action: 'login', ...})
 *
 * apiGet(url, params)
 *   - Makes GET request for read-only data fetching
 *   - Converts params object to query string
 *   - Returns parsed JSON response
 *   - Used for: loading orders, services, dashboard stats
 *   - Example: await apiGet('./php/orders.php', {action: 'get_orders'})
 *
 * ============================================================
 * SECTION 4: TOAST NOTIFICATIONS (Lines 51-79)
 * ============================================================
 *
 * ToastManager Object
 *   - Creates and manages toast notification popups
 *   - Auto-creates toast container if not present
 *   - Types: 'success', 'error', 'info', 'warning'
 *   - Icons: ✓ (success), ✕ (error),  (info), ⚠ (warning)
 *   - Auto-dismisses after duration (default 4.5 seconds)
 *   - Uses textContent for messages (XSS-safe)
 *   - Example: ToastManager.show('Order placed!', 'success')
 *
 * ============================================================
 * SECTION 5: UI COMPONENT HELPERS (Lines 81-238)
 * ============================================================
 *
 * setLoading(btn, loading)
 *   - Shows loading state on buttons during async operations
 *   - Saves original button HTML, disables button, adds CSS class
 *   - Restores original state when loading completes
 *   - Prevents double-submission of forms
 *   - Example: setLoading(submitBtn, true) ... setLoading(submitBtn, false)
 *
 * initNavbar()
 *   - Adds 'scrolled' class to navbar when page scrolls > 40px
 *   - Changes navbar background from transparent to solid white
 *   - Uses passive scroll listener for performance
 *
 * initMobileMenu()
 *   - Handles hamburger menu toggle on mobile devices
 *   - Opens/closes mobile navigation overlay
 *   - Closes menu when clicking outside or on a link
 *   - Updates ARIA attributes for accessibility
 *
 * initServiceCards()
 *   - Implements accordion behavior for service cards on homepage
 *   - Only one card can be expanded at a time
 *   - Supports keyboard navigation (Enter/Space to toggle)
 *   - Updates aria-expanded attribute for screen readers
 *
 * initScrollAnimations()
 *   - Adds fade-in animations to elements as they scroll into view
 *   - Uses IntersectionObserver for performance (threshold: 0.1)
 *   - Falls back to immediate visibility if IntersectionObserver unsupported
 *   - Adds 'visible' class to trigger CSS transitions
 *
 * openModal(id) / closeModal(id)
 *   - Opens/closes modal dialogs by ID
 *   - Prevents body scrolling when modal is open
 *   - Closes on overlay click or Escape key press
 *   - Example: openModal('orderModal') shows order details popup
 *
 * initPasswordToggles()
 *   - Adds show/hide functionality to password input fields
 *   - Toggles input type between 'password' and 'text'
 *   - Updates button icon (👁️ ↔ 🙈) and aria-label
 *   - Finds inputs via data-target attribute on toggle buttons
 *
 * initOTPInputs()
 *   - Implements 6-digit OTP input with auto-advance
 *   - Allows only numeric input (filters non-digits)
 *   - Auto-focuses next input when digit entered
 *   - Backspace moves focus to previous input
 *   - Supports paste: splits pasted text across all 6 inputs
 *   - Example: User pastes "123456" → fills all 6 boxes
 *
 * getOTPValue()
 *   - Collects values from all OTP input boxes
 *   - Returns concatenated 6-digit string
 *   - Example: Returns "123456" from six separate inputs
 *
 * startCountdown(elementId, seconds)
 *   - Displays countdown timer on OTP resend button
 *   - Disables button during countdown (pointer-events: none)
 *   - Shows "Resend in Xs" text
 *   - Re-enables button when countdown reaches 0
 *   - Example: startCountdown('resendBtn', 60) for 60-second cooldown
 *
 * ============================================================
 * SECTION 6: FORMATTERS (Lines 240-253)
 * ============================================================
 *
 * formatNPR(amount)
 *   - Formats number as Nepali Rupees (NPR)
 *   - Uses Indian locale for comma separation (en-IN)
 *   - Shows 0-2 decimal places as needed
 *   - Example: formatNPR(1500) returns "NPR 1,500"
 *
 * formatDate(dateStr)
 *   - Formats date string to readable format
 *   - Returns "DD Mon YYYY" format (e.g., "10 Aug 2026")
 *   - Returns em-dash (—) if date is null/invalid
 *   - Example: formatDate('2026-08-10') returns "10 Aug 2026"
 *
 * ============================================================
 * SECTION 7: STATUS CONFIGURATION (Lines 255-264)
 * ============================================================
 *
 * STATUS_CONFIG Object
 *   - Maps order status codes to display labels and icons
 *   - Used for status badges throughout the application
 *   - Statuses: pending, confirmed, picked_up, in_process, ready, delivered, cancelled
 *   - Icons: 📋 Pending, ✅ Confirmed, 🚗 Picked Up, 🧺 In Process,
 *            ✨ Ready, 🎉 Delivered, ❌ Cancelled
 *
 * ============================================================
 * SECTION 8: FORM HANDLING (Lines 266-332)
 * ============================================================
 *
 * initContactForm()
 *   - Handles contact form submission on homepage
 *   - Sends form data via AJAX to php/contact.php
 *   - Shows success toast or field-level errors
 *   - Clears form on successful submission
 *   - Example: User fills name/email/message → submits → sees toast
 *
 * showAlert(containerId, message, type)
 *   - Displays alert message in specified container
 *   - Types: 'error' (red), 'success' (green), 'warning' (yellow)
 *   - Uses textContent for message (XSS-safe)
 *   - Clears previous alerts before showing new one
 *   - Example: showAlert('loginAlert', 'Invalid password', 'error')
 *
 * showFieldErrors(fields)
 *   - Displays validation errors below form fields
 *   - Highlights error fields with red border
 *   - Creates error message div below each invalid field
 *   - Auto-focuses first error field
 *   - Example: showFieldErrors({email: 'Invalid email format'})
 *
 * clearFieldErrors()
 *   - Removes all field-level error indicators
 *   - Clears error CSS classes and error message divs
 *   - Called before new form submission to reset state
 *
 * ============================================================
 * SECTION 9: INITIALIZATION (Lines 334-349)
 * ============================================================
 *
 * DOMContentLoaded Event Handler
 *   - Runs when HTML document is fully loaded and parsed
 *   - Initializes all UI components in correct order:
 *     1. ToastManager.init() - Setup notification container
 *     2. initNavbar() - Setup scroll-based navbar styling
 *     3. initMobileMenu() - Setup hamburger menu
 *     4. initServiceCards() - Setup service accordion
 *     5. initScrollAnimations() - Setup fade-in animations
 *     6. initPasswordToggles() - Setup password show/hide
 *     7. initOTPInputs() - Setup OTP input behavior
 *     8. initContactForm() - Setup contact form handler
 *
 * Exit Animation Keyframe
 *   - Injects @keyframes slideOutRight animation
 *   - Used for toast notification exit animation
 *   - Fades out and slides right over 0.3 seconds
 *
 * ============================================================
 * SECURITY FEATURES:
 * ============================================================
 * - All user input escaped with escHtml() or textContent
 * - CSRF token automatically included in all POST requests
 * - No eval() or dangerous DOM manipulation
 * - Password fields use appropriate autocomplete attributes
 * - Form validation on both client and server side
 * - XSS prevention through consistent use of safe DOM methods
 *
 * COMPATIBILITY:
 * - Works on all modern browsers (Chrome, Firefox, Safari, Edge)
 * - Graceful degradation for IntersectionObserver (scroll animations)
 * - Passive event listeners for scroll performance
 * - CSS.escape() for dynamic selector generation
 *
 * DEPENDENCIES:
 * - No external JavaScript libraries required
 * - Uses native Fetch API for HTTP requests
 * - Uses native DOM APIs (no jQuery)
 * - Leaflet.js loaded separately for map features (in dashboard.php)
 * ============================================================
 */

// ============================================================
// DD Laundry — main.js  (XSS-safe, CSRF-aware)
// ============================================================
